### ISSUE TITLE
Invalid output for template string

### ISSUE THREAD

**Issue by ikokostya** [cst/cst#100]
Test:

```js
var cst = require('cst');
var Parser = cst.Parser;

var parser = new Parser();
var program = parser.parse('`${1}`');
console.log(program.sourceCode);
```

**Output**

```
`template${1}template`
```

**Expected output**

```js
`${1}`
```

**Comment by hzoo** [comment]
Probably has to do with https://github.com/cst/cst/blob/2abb78ed1379cb0e523fb8ce94862db2d6a6c68e/src/elementTree.js#L221

**Comment by mdevils** [comment]
@ikokostya will you have some time to make a fix?
