### ISSUE TITLE
Remove babel-runtime if possible

### ISSUE THREAD

**Issue by hzoo** [cst/cst#111]
- Remove Array.from, for of loops which use Symbols

**Comment by markelog** [comment]
Why?

**Comment by hzoo** [comment]
just to make the build smaller/one less dependency

**Comment by markelog** [comment]
Are you planning to tackle it?

**Comment by hzoo** [comment]
I started in https://github.com/cst/cst/commit/36b867199529d2ead3b481f1d8468f81c036d855 but [...a] can be slow too since it copies. We can close too

**Comment by markelog** [comment]
> can be slow too since it copies

/cc @mdevils

**Comment by wooorm** [comment]
@markelog @hzoo This breaks I believe jscs, and of course other dependencies of `cst`, on all node versions below 4. I believe jscs-dev/node-jscs/issues/2278 is related.

Now, I don’t care much for those lower versions, other than that I know that others do use them. I’d like to test my libraries in those environments. What are your thoughts on this?

**Comment by markelog** [comment]
Well ESLint recently drop support for it - https://github.com/eslint/eslint/commit/58542e41528157eb2abe41c764cf2576ce2e338f and LTS for those versions will expired less than in three months

**Comment by wooorm** [comment]
@markelog That’s a fine change but not in a SemVer patch release! This is very breaking and should be in a major release.

**Comment by markelog** [comment]
That's debatable, but i already published patched version.

For the future references, can you gave me a link on http://semver.org/ where it says that?

**Comment by wooorm** [comment]
[“MAJOR version when you make incompatible API changes”](http://semver.org).

The interface here is the CLI, which I ran 2 hours ago and it worked; now, when I run it again, it doesn’t. That’s quite breaking.

Take ESLint as an example, they’re releasing a major version too: https://github.com/eslint/eslint/issues/4483#issuecomment-209165289.

**Comment by markelog** [comment]
I get your point and i agree it is breaking, but i didn't change the api so it seems our definition and semver one is different.

Anyways, i think you get what i'm trying to say, also created issue in semver repo - https://github.com/mojombo/semver/issues/317

**Comment by wooorm** [comment]
@markelog I personally interpret API more as “interface” in general, whether GUI, CLI, or API. But is see the confusion.

Also: is a revert expected, or not?

**Comment by markelog** [comment]
well, i already mentioned - https://github.com/cst/cst/issues/111#issuecomment-227784942

should be reverted and published as 0.4.2, does it work for you?

**Comment by wooorm** [comment]
Oh whooops, sorry, missed that! Thanks, yeah that works for me! 👍
