### ISSUE TITLE
Destructuring with default values in parameters throws an error.

### ISSUE THREAD

**Issue by graingert** [cst/cst#126]
#118 was not fixed:

with
```js
function a ({ foo = false, bar = null } = {}) {
    console.log(bar);
}
```

I still get:

```
$ npm install
$ ./node_modules/.bin/jscs src
Expected token value ":" but = found at src/all.es :
     1 |function a ({ foo = false, bar = null } = {}) {
--------^
     2 |    console.log(bar);
     3 |}
```

see https://github.com/graingert/jscs-error/tree/4b12b5da89e5dc429980f097ef73bc1e855a9c60
This is jscs 3.0.5 with cst 0.4.0

see also https://github.com/jscs-dev/node-jscs/issues/2277 and #118

**Comment by graingert** [comment]
@markelog looks like it's the "const" keyword here.

**Comment by markelog** [comment]
hm, weird, could you try it with latest master?

**Comment by graingert** [comment]
Can you repeat the error with https://github.com/graingert/jscs-error/tree/4b12b5da89e5dc429980f097ef73bc1e855a9c60 ?

**Comment by markelog** [comment]
The weird thing is it works for me locally i.e. with `npm link <path>/cst` but didn't work with cst 0.4.0 if downloaded from npm, even though it should be the same code.

Now it works with 0.4.1, i would like to verify it though before releasing jscs 3.0.6

**Comment by graingert** [comment]
@markelog works here: https://github.com/graingert/jscs-error/tree/50f927259be6bc6a8166d41ee55bc763263d8ddf

**Comment by graingert** [comment]
@markelog looks like 0.4.0 points to stale code. Maybe lib didn't build? Could you update the git tag to match the version that is on NPM? Might be worth deleting 0.4.0 too as it's invalid.

**Comment by graingert** [comment]
It looks like the files in https://registry.npmjs.org/cst/-/cst-0.4.0.tgz were built on the 19th June, but the source fix went in on the 20th June.

**Comment by markelog** [comment]
This is weird indeed, i think i was on buggy npm version, since i also noted other peculiar issues with it, git tag points to the correct commit though, i don't think it warrants a republishing though.

btw "npm" should be written with lowercase :)

**Comment by graingert** [comment]
Your comment is quite "I"ronic

**Comment by graingert** [comment]
I don't think it's worth re-release, maybe a delete?

**Comment by markelog** [comment]
Wouldn't it break for people who use shrinkwrap or exact versions of CST? It seems that 0.4.0 version doesn't break people code in the same way 0.3.0 doesn't break code, seems risky

**Comment by graingert** [comment]
@markelog an upgraded JSCS would fix the issues I'm having trying to distribute the updated CST module to the rest of my team.
