### ISSUE TITLE
cst 0.4.1 breaks jscs 3.0.5

### ISSUE THREAD

**Issue by cscott** [cst/cst#128]
The 0.4.0 release of cst has the following deps:
```
cst@0.4.0 (babylon@6.8.1, source-map-support@0.4.0, babel-types@6.10.2, babel-runtime@6.9.2)
```
The 0.4.1 release of cst has the (smaller) dep set:
```
cst@0.4.1 (source-map-support@0.4.0, babylon@6.8.1)
```
This breaks jscs 3.0.5 (see https://github.com/jscs-dev/node-jscs/issues/2278).

**Comment by cscott** [comment]
Root cause seems to be https://github.com/cst/cst/issues/111, which breaks node < 4.

**Comment by markelog** [comment]
Okay, three people reported about this, will revert
