### ISSUE TITLE
Migrate to ESLint from JSCS

### ISSUE THREAD

**Issue by paazmaya** [cst/cst#139]
http://eslint.org/blog/2016/07/jscs-end-of-life

Perhaps start of by using the `recommended` preset...

I am willing to do a PR in case this seems like a reasonable issue.

**Comment by markelog** [comment]
We currently use `google` preset, we can try eslint version here as well, https://github.com/brenolf/polyjuice might be handy for other code style inconsistencies.

But there probably will be a lot of non-code style issues...

PR surely welcome

**Comment by paazmaya** [comment]
Without `recommended` preset: 126 problems (126 errors, 0 warnings)

With `recommended` preset: 981 problems (981 errors, 0 warnings)

**Comment by paazmaya** [comment]
Added `node` environment and changed `no-unused-vars` and `valid-jsdoc` to warnings: 158 problems (16 errors, 142 warnings)

Sadly only one of the above errors was autofixable via `eslint --fix`

**Comment by paazmaya** [comment]
Seems like Flow types need a plugin https://www.npmjs.com/package/eslint-plugin-flowtype

**Comment by hzoo** [comment]
https://github.com/cst/cst/pull/140
