### ISSUE TITLE
selectNodesByType does not return prepended nodes in correct order

### ISSUE THREAD

**Issue by Smolations** [cst/cst#147]
So, I'm working on a project where I need to modify an existing file and add an import statement, and ensure that all import statements remain in alphabetical (lexigraphical) order. However, things aren't working as expected, apparently due to `Program.prototype.selectNodesByType()`.

Here's the source file to be modified (`src/components/module.es6.js`):
```javascript
import angular from 'angular';
import bounceLoaderModule from './bounce-loader/module.es6';


export default angular.module('components', [
  bounceLoaderModule
])

  .name;

```

And here's my test file:
```javascript
const cst = require('cst');
const cstUtil = require('./lib/cst-util.es6');
const fs = require('fs');

const fileContents = fs.readFileSync('src/components/module.es6.js', { encoding: 'utf8' });
const parser = new cst.Parser();

let program = parser.parse(fileContents);
let updatedProgram = cstUtil.addImport(program, 'billy', './clubs/billy'); // silliness, but should be 2nd module declaration

console.log(updatedProgram.getSourceCode());
```

To keep the test file (the code of which will eventually end up in a yeoman generator) clean, I've created a utility object to help with the common operations. And here are the pertinent contents of that file (`./lib/cst-util.es6`):
```javascript
// ...imports and whatnot
module.exports = {
  addImport: function(program, identifier, identifierPath) {
    // this returns an already-tested, correct ImportDeclaration
    var moduleDec = this.importDeclaration(identifier, identifierPath);
    var newline = this.newline();  // valid whitespace Token

    program.prependChild(newline);
    program.prependChild(moduleDec);

    var imports = program.selectNodesByType('ImportDeclaration');
    var importsClone = imports.map((el, index) => {
      console.log(index + ': ' + el.getSourceCode())
      return el.cloneElement();
    });

    // will sort lexigraphically by import specifier
    importsClone.sort((el1, el2) => { /* works; see console output */});

    console.log('------------------------------------------------');

    imports.forEach((el, index) => {
      console.log(index + ': ' + importsClone[index].getSourceCode())
      program.replaceChild(importsClone[index], el);
    });

    console.log('------------------------------------------------');

    return program;
  },
  // ...more helpers...
```

And finally, here's what I'm seeing in the console:
```
0: import angular from 'angular';
1: import bounceLoaderModule from './bounce-loader/module.es6';
2: import billy from './dudes/billy';
------------------------------------------------
0: import angular from 'angular';
1: import billy from './dudes/billy';
2: import bounceLoaderModule from './bounce-loader/module.es6';
------------------------------------------------
import bounceLoaderModule from './bounce-loader/module.es6';
import angular from 'angular';
import billy from './dudes/billy';


export default angular.module('elmer.components', [
  bounceLoaderModule
])

  .name;

```

When I tried returning the `program` immediately after the two `.prependChild()` calls, the new import statement was indeed at the top of the source code in the console output. However, from the original console output you can see that `program.selectNodesByType('ImportDeclaration');` returns an array with the new import as the _last_ element in the array (presumably because it was the last element added to the program?). And, even though the sort function sorts the array correctly, when I try replacing elements the order is completely off. With a rudimentary change, I was able to to get the desired result by altering the logic at the top of the `addImport()` function:
```javascript
  addImport: function(program, identifier, identifierPath) {
    var moduleDec = this.importDeclaration(identifier, identifierPath);
    var newline = this.newline();

    var imports = program.selectNodesByType('ImportDeclaration');
    imports.unshift(moduleDec);

    var importsClone = imports.map((el, index) => {
      console.log(index+': '+el.getSourceCode())
      return el.cloneElement();
    });

    program.prependChild(newline);
    program.prependChild(moduleDec);

    importsClone.sort((el1, el2) => { /* ... */ });
    // ...same code as above...
```

Secondary question...while I was troubleshooting, I was in `Traverse.js` and looked at the constructor:
```javascript
constructor() {
  this._nodeIndex = new ElementIndexByType();
  this._tokenIndex = new ElementIndexByType();
}
```

I could not for the life of me find the definition of `ElementIndexByType` in the repo, in babylon's repo, or doing a google search. Where in the heck does that come from??

**Comment by markelog** [comment]
Yeah, that's a bug, [this](https://github.com/cst/cst/pull/150) should fix things up

> Where in the heck does that come from??

Same file, close to EOF

**Comment by Smolations** [comment]
Awesome, thanks for getting the fix out so quickly!

> Same file, close to EOF :)

LOL! When i searched the repository it only showed code up by the constructor. Maybe next time I should just fuzzy search the project in Sublime!  🙈
