### ISSUE TITLE
v0.4.8 is missing lib folder

### ISSUE THREAD

**Issue by ShyykoSerhiy** [cst/cst#151]
How to reproduce:
npm i cst@0.4.8 && ls ./node_modules/cst
temp@0.0.1 /somepath/temp
└── cst@0.4.8

npm WARN temp@0.0.1 No repository field.
npm WARN temp@0.0.1 No license field.
LICENSE      README.md    node_modules package.json

**Comment by ShyykoSerhiy** [comment]
Looks like the it's the same story as in https://github.com/cst/cst/issues/134.

**Comment by hzoo** [comment]
https://unpkg.com/cst@0.4.8/ right

**Comment by hzoo** [comment]
published https://unpkg.com/cst@0.4.9/
