### ISSUE TITLE
weird message Expected end of node list but "CommentBlock" found in jsx file

### ISSUE THREAD

**Issue by joseph-jja** [cst/cst#154]
however line 1 is an empty line.  It seems that no matter what it fails at this line

I tracked it down to cst/lib/elements/ElementAssert.js as the file that the error is coming from, but have no idea why it fails on a simple jsx file.

**Comment by markelog** [comment]
> however line 1 is an empty line. It seems that no matter what it fails at this line

What line?

**Comment by joseph-jja** [comment]
If I have a file 

1 var Header = function () {
2 
3 }

 where the 1, 2, and 3 are the line numbers, not part of the actual code.  Line 1 would be on the var that jscs errors out in the ElementAssert.js

**Comment by joseph-jja** [comment]
OK, so if I use     "esprima": "esprima-fb", in the jscs config file and run jscs on the command line then jscs processes the files correctly, but if I run via npm run jscs it errors out with the above message from cst.  So there is something in cst that is conflicting with something else and causing this issue.

**Comment by markelog** [comment]
Sounds like you use old version of jscs, since `esprima` property refers to parser you use, which doesn't makes sense for jscs 3.0 that property was removed in that version

**Comment by joseph-jja** [comment]
I was using jscs 3.0.7 and having this issue, when I downgrade to jscs 2.11.0 I then add  esprima line in my code it works fine.
