### ISSUE TITLE
Implement JSX Nodes

### ISSUE THREAD

**Issue by mdevils** [cst/cst#3]

**Comment by mdevils** [comment]
We probably should implement JSX in a separate module?

**Comment by hzoo** [comment]
https://facebook.github.io/jsx/

https://github.com/babel/babel/blob/91e59cf2bb90f6e5ae2235bcbe748fedf7f983c9/packages/babel/src/types/definitions/jsx.js

https://github.com/RReverser/acorn-jsx/blob/master/inject.js

**Comment by hzoo** [comment]
Oh we can close this now!
