### ISSUE TITLE
ES6: Template Strings

### ISSUE THREAD

**Issue by mdevils** [cst/cst#35]
We need to implement nodes for:

```
    /*--*/ TaggedTemplateExpression: ['tag', 'quasi'],
    /*--*/ TemplateElement: [],
    /*--*/ TemplateLiteral: ['quasis', 'expressions'],
```

**Comment by markelog** [comment]
Will check it out tomorrow

**Comment by hzoo** [comment]
So implementing might be ok but we will probably need to do a conversion from babel/acorn -> esprima. I finished porting it to a package so we might need https://github.com/babel/acorn-to-esprima/blob/master/src/convertTemplateType.js.

Repo: https://github.com/babel/acorn-to-esprima

I can probably update https://github.com/babel/acorn-to-esprima/blob/master/src/toToken.js to what we have so we can just use that instead https://github.com/cst/cst/blob/master/src/elementTree.js#L242-L308

**Comment by mdevils** [comment]
Why do we need to convert? The only thing we need to follow is `ESTREE`

**Comment by hzoo** [comment]
We might not have to? We'll see when you try to integrate with jscs? It's like the https://github.com/babel/acorn-to-esprima/blob/master/src/toToken.js we added in.

**Comment by mdevils** [comment]
We will just change jscs code (it's required anyway). Let's stick to `estree` spec, it has better decisions.

>  It's like the https://github.com/babel/acorn-to-esprima/blob/master/src/toToken.js we added in.

It was more to avoid Acorn's strange tokens and stick to more convenient Esprima tokens.

**Comment by hzoo** [comment]
> It was more to avoid Acorn's strange tokens and stick to more convenient Esprima tokens.

Yeah I just updated my comment - this would be exactly for what you said.

**Comment by mdevils** [comment]
Strange tokens we have in Acorn this time... what is this: `{ type: 'Punctuator', value: 'template' },`?

**Comment by mdevils** [comment]
Overall in this case I think Acorn's tokens are more useful (except for mysterious `{ type: 'Punctuator', value: 'template' }`)

**Comment by hzoo** [comment]
It looks like the Literal node has a property `regex`? https://github.com/estree/estree/blob/master/spec.md#literal

In esprima and babel for `/a/`
```
{
    "type": "ExpressionStatement",
    "expression": {
        "type": "Literal",
        "value": "/a/",
        "raw": "/a/",
        "regex": {
            "pattern": "a",
            "flags": ""
        }
    }
}
```
