### ISSUE TITLE
ES7: Async/Await Elements

### ISSUE THREAD

**Issue by mdevils** [cst/cst#49]

**Comment by hzoo** [comment]
https://github.com/tc39/ecmascript-asyncawait - stage 2 currently.

**Comment by hzoo** [comment]
We can use stages instead of es7 (also its stage 3 now!)

**Comment by hzoo** [comment]
Ok https://github.com/rwaldron/tc39-notes/blob/master/es7/2015-07/july-30.md#64-advance-async-functions-to-stage-2

I guess `await*` is gone
