### ISSUE TITLE
Stage 2: Rest/Spread Properties

### ISSUE THREAD

**Issue by hzoo** [cst/cst#51]
https://github.com/sebmarkbage/ecmascript-rest-spread

Will be `babel-plugin-transform-object-rest-spread` in babel 6.0

```js
// rest
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
// spread
let n = { x, y, ...z };
```

Currently only `SpreadProperty` in [babel 5](https://github.com/babel/babel/blob/31a01cc4d257e8d9237b02c5469c2cd7ce2d2abb/packages/babel/src/types/definitions/experimental.js#L31-L34)

And will become `SpreadProperty` and `RestProperty` in [babel 6](https://github.com/babel/babel/blob/227ed5638ae1269713df7cb9e0da317761b02a4b/packages/babel-types/src/definitions/experimental.js#L79-L97)

**Comment by mdevils** [comment]
Great job! Check two notes which I left for this PR.
