### ISSUE TITLE
Replace visitorKeys with babel-types package

### ISSUE THREAD

**Issue by hzoo** [cst/cst#56]
After babel 6.0, we can use https://github.com/babel/babel/tree/development/packages/babel-types.

And maybe we want a way to make sure each property is used in cst so we can easily know if we missed something if babel updates (if ES6+ visitorKeys change)

I guess this is similar to #23

**Comment by mdevils** [comment]
I think we can do this now

**Comment by hzoo** [comment]
This can be done in https://github.com/cst/cst/pull/96
