### ISSUE TITLE
Your demo image uses comic sans.

### ISSUE THREAD

**Issue by CodeLuca** [cst/cst#60]
https://raw.githubusercontent.com/cst/cst/master/docs/cst-example.png

**Comment by mdevils** [comment]
And what's wrong with it?)

**Comment by CodeLuca** [comment]
It's Comic Sans.

**Comment by CodeLuca** [comment]
Sadly, your a: http://www.comicsanscriminal.com/

**Comment by CodeLuca** [comment]
I'm sorry this issue is just a little bit of a joke :)

**Comment by mdevils** [comment]
OK, ha-ha :smile:

**Comment by forivall** [comment]
and there came a voice from the heavens, and it said: http://comicneue.com
