### ISSUE TITLE
Question about customizing parsing

### ISSUE THREAD

**Issue by mark-hahn** [cst/cst#63]
I was elated to discover this project.  It does exactly what I need for a project I just started two days ago (https://github.com/mark-hahn/jsw).  I have spent the last two days investigating how to do a round trip from JS code to AST and back while preserving the original text.  This was needed to avoid unnecessary git diffs.

**A question:**

I need to modify the CST to output a slightly different syntax than JS and this project will make that trivial.  However, I will also need to later parse my modified syntax back into a CST.  It is not obvious how I should do this.

Can anyone offer any suggestions for customizing the parsing into a CST?

**Comment by mark-hahn** [comment]
After reading code I see that I need to write a plugin for the babel parser.

**Comment by hzoo** [comment]
Ah yeah this is like an augmented AST that includes whitespace but only knows about babel supported syntax
