### ISSUE TITLE
Pluggable parser support

### ISSUE THREAD

**Issue by RReverser** [cst/cst#75]
Would it be possible to decouple the main logic from parsing itself and provide support for pluggable parsers similarly to ESLint? As far as I understand, they're not hardly linked so far, so should be possible to do as soon as parser emits same AST and tokens format.

**Comment by hzoo** [comment]
Yeah I think so. Don't know when I'l be able to merge https://github.com/cst/cst/pull/73. I'm not sure what we would do about how object rest/spread is different in eslint.

**Comment by RReverser** [comment]
How is it different?

**Comment by hzoo** [comment]
Nvm the ast is the probably same I just was thinking we had to map the type to `SpreadProperty` and `RestProperty`

**Comment by markelog** [comment]
> As far as I understand, they're not hardly linked so far, so should be possible to do as soon as parser emits same AST and tokens format

Since now we are using babylon and it seems babylon will never output same AST/tokens.

**Comment by RReverser** [comment]
That's pretty sad. Can't you use ESTree standard and convert from anything else using adapters that already exist for ESLint?

**Comment by markelog** [comment]
> That's pretty sad.

Totally :/

I guess it could be done as a plugin (plugin system should be done after the next weekend), that plugin could convert and provide different parser.

**Comment by RReverser** [comment]
> that plugin could convert and provide different parser

Except that ESLint has bunch of adapters (Acorn, Babylon, Esprima, even TypeScript) around it already that could be reused, while plugin would need either to add enother level of abstraction between them and cst or each adapter needs to be reimplemented as plugin for cst :(

**Comment by markelog** [comment]
So... do you have an idea how to make it work?
