### ISSUE TITLE
removeChild vs removeToken

### ISSUE THREAD

**Issue by markelog** [cst/cst#77]
It seems we need a `removeToken` method, just like the one we have in JSCS.

Right now, probably as expected, this -
```js
let program = parseAndGetProgram('var first = 1; var second = 2;');
program.removeChild(program.firstToken); //  Error: The element to be removed is not a child of this element.
```

Doesn't work.

@mdevils thoughts?

**Comment by mdevils** [comment]
Removing tokens (or nodes, or anything..):

```js
program.firstToken.parentElement.removeChild(program.firstToken);
```

**Comment by markelog** [comment]
`program.firstToken.parentElement` should be `program`. Why not?

Your example also doesn't work - 
```js
let program = parseAndGetProgram(';');
program.firstToken.parentElement.removeChild(program.firstToken);
```

**Comment by mdevils** [comment]
```
Program
  VariableDeclaration
    Token (var) // First token
    VariableDeclarator
        ...
```

**Comment by markelog** [comment]
I see, how about examples?

**Comment by mdevils** [comment]
```js
let program = parseAndGetProgram(';');
// Error: Token expected but "undefined" found
program.firstToken.parentElement.removeChild(program.firstToken);
```

In this example:

```
Program
  EmptyStatement
    Token (;)
```

You remove token from EmptyStatement, but EmptyStatement is invalid without a single `;` token, that's why you get assertion error.

The same thing here:

```js
// Or with
let program = parseAndGetProgram('var first = 1;');
program.firstToken.parentElement.removeChild(program.firstToken);

// Error: Expected token type "Keyword" but "Whitespace" found
```

You remove var token and make CST invalid. This is not allowed. You cannot break CST structure.

**Comment by markelog** [comment]
So how can i remove the `;` token, without removing the `node`?

**Comment by mdevils** [comment]
> So how can i remove the ; token, without removing the node in first example?

You should remove the node.
