### ISSUE TITLE
Generator method property should have correct `generator` value

### ISSUE THREAD

**Issue by markelog** [cst/cst#86]
For the 
```js
({ * foo() {} })
```
`FunctionExpression` node will have `generator = false`. Whereas it should be `true`. `FunctionExpression` constructor doesn't receive that knowledge. So i'm not sure how to corrected it.

**Comment by hzoo** [comment]
Might just have to add a new case in `FunctionExpression` with the `*` being first for the shorthand generator syntax?

**Comment by markelog** [comment]
Not sure what do you mean by that

**Comment by hzoo** [comment]
Just saying I think we would need to just modify https://github.com/cst/cst/blob/master/src/elements/types/FunctionExpression.js#L18-L48

**Comment by mdevils** [comment]
I will fix this, need to figure out how. Because this part of `Property` is not in `FunctionExpression` range.

**Comment by markelog** [comment]
Yeah, that what i have meant by 

> FunctionExpression constructor doesn't receive that knowledge.

**Comment by mdevils** [comment]
I guess this case is a flaw of the ESTree AST itself unfortunately (and I think it's fixed in new babel6 AST).

So I would suggest to hack it and introduce a hidden flag `_generator` in `Property`.
