### ISSUE TITLE
[Question] Plan to support node 0.10?

### ISSUE THREAD

**Issue by ficristo** [cst/cst#87]
Do you plan to still support node 0.10?
I was messing with a small project of mine and I found my node complained about `Symbol`

**Comment by markelog** [comment]
.10 is supported, could you show some code?

**Comment by ficristo** [comment]
With latest version (0.0.15), the following code fail.
```javascript
var cst = require('cst');
var parser = new cst.Parser();
var tree = parser.parse('var foo = 0');
```
With this error: `ReferenceError: Symbol is not defined`

**Comment by ficristo** [comment]
It seems it is necessary to include the babel polyfill but I didn't understood how I could do for babel 5.
I thought adding an import to `src/index.js` was sufficient but it is not (or I've added it wrongly...).

**Comment by markelog** [comment]
The issue with it, that we use `register-babel` to run tests which would conflict with babel `Symbol` polyfill, we need to figure this out in other words :)

> Guess, we also need to support 0.8

Wouldn't want that, why?

**Comment by zxqfox** [comment]
Because there are no significant differences between 0.10 and 0.8

**Comment by ljharb** [comment]
`Symbol` shouldn't be polyfilled anyways since it can't be made to be spec-compliant.

It would be ideal to support as old a node as possible.

**Comment by markelog** [comment]
> Because there are no significant differences between 0.10 and 0.8

That is **really** debatable statement and i **really** don't want argue about this, ad nauseam and all that. Bottom line is, if there will be significant amount of users w that version, then i think we should support it, but i highly doubt we would.

> Symbol shouldn't be polyfilled anyways since it can't be made to be spec-compliant.

Sounds like you saying - we either shouldn't use it, or shouldn't support the old nodes i.e. you saying we shouldn't use it?

**Comment by ljharb** [comment]
I'm saying you should not use Symbols internally.

**Comment by ficristo** [comment]
From what I've undersood:
- Symbols aren't used internally but used by the generated code by Babel 5.
- I've written about polyfill because different people had similar problems like this one and always pointed out about babel polyfill.
- In Babel 6 some of these are fixed, so maybe it is enough waiting for https://github.com/cst/cst/pull/73

**Comment by hzoo** [comment]
@ficristo - made a prerelease version (0.0.25-1) with babel runtime plugin which should allow node 0.10 (I tested by using node-jscs, and it passed in travis when it was failing before).

**Comment by ficristo** [comment]
I need to add the babel runtime to make it work.
```javascript
"dependencies" : {
    "cst": "0.0.25-1",
    "babel-runtime": "^5.0.0"
}
```
Without it complains with:
`Cannot find module 'babel-runtime/helpers/interop-require-default'`

**Comment by hzoo** [comment]
Ah good catch (I put babel-runtime in the devdependencies of cst, not the dependencies so you would have to install it on the user side). I will change that so you don't have to do that.

**Comment by hzoo** [comment]
K closing
