### ISSUE TITLE
Allow addition of whitespace and punctuators token to the end of the property element

### ISSUE THREAD

**Issue by markelog** [cst/cst#89]
If -
```js
var obj = {foo: "foo"};
```

Then it should be allowed to do 
```js
comma = new cst.Token('Punctuator', ',');
Property.appendChild(comma) // or whitespace
```

/cc @mdevils

**Comment by hzoo** [comment]
Hmm yeah since we are checking for a trailing comma in `ObjectExpression` instead of `Property` like in https://github.com/cst/cst/blob/master/src/elements/types/ObjectExpression.js#L25-L29 and https://github.com/cst/cst/blob/master/test/lib/elements/types/ObjectExpression.js#L19

**Comment by mdevils** [comment]
@hzoo yes, you are correct. You should insert comma into `ObjectExpression` before `}` token.

**Comment by markelog** [comment]
Okay, added a test and how to - https://github.com/cst/cst/wiki/How-to-add-a-property-to-an-object

If there anything to correct, feel free and all that
