### ISSUE TITLE
How to make property into shorthand

### ISSUE THREAD

**Issue by markelog** [cst/cst#90]
Basically, i would like to know how we can make 
```js
// this 
({ foo: foo })

// into this -
({ foo })
```

And vice versa

@mdevils ?

**Comment by mdevils** [comment]
Form a new Property and replace the old Property with the new one.

i.e. `parent.replaceChild(new Property([new Identifier([new Token('foo')])]), oldProperty);`

**Comment by markelog** [comment]
You can also replace the token right?

Will leave this open and close it after i will document it.

**Comment by markelog** [comment]
> You can also replace the token right?

I suppose that would mean user would also need to change internal `_shorthand` property :/

**Comment by mdevils** [comment]
@markelog yes, you can also remove all the Elements after the first Identifier node.

**Comment by mdevils** [comment]
> I suppose that would mean user would also need to change internal _shorthand property :/

This is not the case for CST, you cannot always rebuild tokens on property changes because style differs.

**Comment by mdevils** [comment]
@markelog once you modify Property's content, _shorthand property will be recalculated.

**Comment by markelog** [comment]
Stuff like this -
```js
new cst.types.Property([
    new cst.Token('Identifier', 'foo'),
    new cst.Token('Punctuator', ':'),
    new cst.Token('Identifier', 'foo')
])
```
doesn't work, throws - `Expected token type "Punctuator" but "Identifier" found`

Started searching for error, but instead settled with - 

```js
var parse = require('cst/test/utils').parseAndGetObjectProperty;
parent.replaceChild(parse('({ foo })'), element);
```
Which is muuuuch easier, like innerHTML or something, i think we need to move those helpers outside of the `test` folder

**Comment by mdevils** [comment]
```js
new cst.types.Property([
    new cst.types.Identifier([cst.Token('Identifier', 'foo')]),
    new cst.Token('Punctuator', ':'),
    new cst.types.Identifier([cst.Token('Identifier', 'foo')])
])
```

**Comment by mdevils** [comment]
> Which is muuuuch easier, like innerHTML or something, i think we need to move those helpers outside of the test folder

I'm thinking about introducing `innerCode` property. Not very trivial though.

**Comment by markelog** [comment]
```js
new cst.types.Property([...
```
Throws 
```Cannot call a class as a function```

> I'm thinking about introducing innerCode property. Not very trivial though.
We might make it available only for certain types at the moment, but i'm not sure how it would help for this case

**Comment by mdevils** [comment]
`new` before token constructor was missing:

```js
new cst.types.Property([
    new cst.types.Identifier([new cst.Token('Identifier', 'foo')]),
    new cst.Token('Punctuator', ':'),
    new cst.types.Identifier([new cst.Token('Identifier', 'foo')])
])
```

**Comment by mdevils** [comment]
Closing this. Reopen if you still have questions.
