### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ficristo** [cst/cst#92]
I wanted to look at https://github.com/cst/cst/issues/87 to see if updating some libraries could help.
But I found that Window is not supported:
`flow-bin`
`No binary found matching your system. It's probably not supported.`
It seems there is some work to support Windows platform on `flow-bin` side, so I leave this issue mostly as a tracking one.

**Comment by mdevils** [comment]
Hello.

You can still develop on windows without checking the code with `flow`. I hope `flow` will release a binary for windows soon.
