### ISSUE TITLE
Error: Token expected but "JSXAttribute" found

### ISSUE THREAD

**Issue by roman01la** [cst/cst#93]
Hello! I'm getting the error: `Error: Token expected but "JSXAttribute" found` when parsing the following JSX: `<input type="text" id="input" />`. When I remove `id` attribute, parsing is done without errors.

Is it a known bug or am I doing wrong something?

Here's a snippet of code I'm running.

```js
var Parser = require('cst').Parser;
var parser = new Parser();

parser.parse('<input type="text" id="input" />');
```

**Comment by mdevils** [comment]
Hello!

This is probably a bug. I will look at this soon, thank you.

**Comment by mdevils** [comment]
Fixed in `0.0.17`

**Comment by hzoo** [comment]
Wow my bad that seems like an obvious test

**Comment by roman01la** [comment]
Thanks! 👍
